# Generated by Django 2.2.12 on 2022-10-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=25)),
                ('is_available', models.CharField(max_length=30)),
                ('expire_date', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
